version: '2.3'
services:
  node-screenshots:
    container_name: node-screenshots
    image: valentinvieriu/node-screenshots:1.1.0
    build: .
    # privileged: true
    restart: 'unless-stopped'
    cap_add: 
      - 'SYS_ADMIN'
    # user: pptruser
    shm_size: 2G
    restart: always
    mem_limit: 1G
    memswap_limit: 2G
    environment:
      FILES_CLEAN_TIMEOUT: ${FILES_CLEAN_TIMEOUT}
      # WATCH_QUEUE: ${WATCH_QUEUE}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      REDIS_URL: ${REDIS_URL}
      REMOTE_HOST: chrome-headless
      REMOTE_PORT: 9222
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      - "traefik.port=${PORT}"
      - "traefik.frontend.rule=Host:node-screenshots.${TLD}"
    ports:
      - '${PORT}:${PORT}'
    volumes: 
      - ${ROOT_FOLDER}/screenshots:/usr/src/app/screenshots

networks:
  default:
    external:
      name: ${DOCKER_NETWORK}