version: '3'
services:
  node-screenshots:
    container_name: node-screenshots
    image: valentinvieriu/node-screenshots:1.0.3
    build: .
    # privileged: true
    restart: always
    working_dir: /app
    environment:
      FILES_CLEAN_TIMEOUT: ${FILES_CLEAN_TIMEOUT}
      WATCH_QUEUE: ${WATCH_QUEUE}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      REDIS_URL: ${REDIS_URL}
      REMOTE_HOST: chrome-headless
      REMOTE_PORT: 9222
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      - "traefik.port=${PORT}"
      - "traefik.frontend.rule=Host:node-screenshots.${TLD}"
    # ports:
    #   - '${PORT}:${PORT}'
    volumes: 
      - ${ROOT_FOLDER}/screenshots:/app/screenshots

networks:
  default:
    external:
      name: ${DOCKER_NETWORK}