version: '2'
services:
  chrome-headless:
    container_name: chrome-headless
    image: alpeware/chrome-headless-trunk
    # image: yukinying/chrome-headless
    # image: valentinvieriu/chrome-headless
    # image: justinribeiro/chrome-headless
    build: .
    privileged: true
    restart: always
    # mem_limit: 2G
    # memswap_limit: 0
    command: '--ignore-certificate-errors --no-sandbox --headless --disable-gpu --hide-scrollbars --window-size=1280,1280 --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222'
    # command: '--headless --disable-gpu --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --security-opt seccomp=/chrome.json'
    working_dir: /screenshots
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    labels:
        - "traefik.enable=false"
    ports:
      - '${PORT}:9222'
    volumes: 
      # - ./fetchImages.js:/usr/src/app/fetchImages.js
      - ./screenshots:/screenshots
      - ./chrome.json:/chrome.json
# networks:
#   default:
#     external:
#       name: mainframe_default